DEVICE: cuda:1
SAVE_DIR: 'output'
MODEL:
  NAME: FGMaxxVit_Multi
  BACKBONE: FGMaxxVit
  PRETRAINED: 'checkpoints/pretrained/maxvit_base_tf_512.in1k_pretrained_weights.pth'
  UNFREEZE      : 'encoder.stages.3'                         # Freeze all layers without UNFREEZE ['encoder.stages.0', 'encoder.stages.1', 'encoder.stages.2', 'encoder.stages.3', None]
DATASET:
  NAME          : EpisodicNMCDataset                                          # dataset name to be trained with (camvid, cityscapes, ade20k)
  # ROOT          : '/data/nmc/processed_image'
  ROOT          : '/data/nmc/processed_image'   

  N_WAY: 5 #고유 클래스 개수
  K_SHOT: 3
  Q_QUERY: 15
  MINOR_CLS: [4,5]
  SPLIT_RATIO: 0.75
  
TRAIN:
  IMAGE_SIZE: [512, 512] 
  NUM_EPISODES: 1000  # Total number of episodes
  EVAL_INTERVAL: 10  # Evaluate after every 100 episodes
  AMP: false
  DDP: false

LOSS_CLS:
  NAME          : Contrastive          # loss function name (ohemce, ce, dice)
  CLS_WEIGHTS   : false            # use class weights in loss calculation

LOSS:
  NAME          : BCEWithLogitsLoss          # loss function name (ohemce, ce, dice)

OPTIMIZER:
  NAME          : adamw           # optimizer name
  LR            : 0.0001           # initial learning rate used in optimizer
  WEIGHT_DECAY  : 0.01            # decay rate used in optimizer 

SCHEDULER:
  NAME          : warmuppolylr    # scheduler name
  POWER         : 0.9             # scheduler power
  WARMUP        : 10              # warmup epochs used in scheduler
  WARMUP_RATIO  : 0.1             # warmup ratio
  

EVAL:
  MODEL_PATH    : 'checkpoints/pretrained/FGMaxxVit/FGMaxxVit.FGMaxxVit.NMC.pth'  # trained model file path
  IMAGE_SIZE    : [512, 512]                                                            # evaluation image size in (h, w)                       
  # MSF: 
  #   ENABLE      : false                                                                 # multi-scale and flip evaluation  
  #   FLIP        : true                                                                  # use flip in evaluation  
  #   SCALES      : [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]                                     # scales used in MSF evaluation                


TEST:
  MODEL_PATH    : 'checkpoints/pretrained/FGMaxxVit/FGMaxxVit.FGMaxxVit.NMC.pth'  # trained model file path
  FILE          : 'assests/ade'                                                         # filename or foldername 
  IMAGE_SIZE    : [512, 512]                                                            # inference image size in (h, w)
  OVERLAY       : true       