DEVICE          : cuda:1            # device used for training and evaluation (cpu, cuda, cuda0, cuda1, ...)
SAVE_DIR        : 'output'         # output folder name used for saving the model, logs and inference results

MODEL:                                    
  NAME          : EfficientNetV2MModelMulti           # name of the model you are using #[ResNet50Model, FGMaxxVit, EfficientNetV2MModel, ResNet50MultiHeadModel,EfficientNetV2MModelMulti]
  BACKBONE      : EfficientNetV2                                          # model variant #[ResNet-50, FGMaxxVit, EfficientNetV2]
  # PRETRAINED    : '/workspace/jhmoon/nmc_2024/checkpoints/pretrained/maxvit_base_tf_512.in1k_pretrained_weights.pth'
  # PRETRAINED    : '/workspace/jhmoon/nmc_2024/checkpoints/pretrained/resnet50_a1_in1k_weights.pth'              # backbone model's weight 
  PRETRAINED    : '/workspace/jhmoon/nmc_2024/checkpoints/pretrained/tf_efficientnetv2_m_weights.pth'
  UNFREEZE      : 'full'                     # Freeze all layers without UNFREEZE ['encoder.stages.0', 'encoder.stages.1', 'encoder.stages.2', 'encoder.stages.3', None, 'full']
  VERSION : 384_32_loss'

DATASET:
  NAME          : NMCDataset                                          # dataset name to be trained with (camvid, cityscapes, ade20k)
  # ROOT          : '/data_2/national_AI_DD/nmc/processed_image'
  ROOT          : '/data/nmc/processed_image'                         # dataset root path
  #IGNORE_LABEL  : -1
  TRAIN_RATIO   : 0.7
  VALID_RATIO   : 0.15
  TEST_RATIO    : 0.15

TRAIN:
  IMAGE_SIZE    : [384, 384]      # training image size in (h, w)
  BATCH_SIZE    : 32               # batch size used to train
  EPOCHS        : 100             # number of epochs to train
  EVAL_INTERVAL : 1              # evaluation interval during training
  AMP           : false           # use AMP in training
  DDP           : false           # use DDP training

LOSS:
  NAME          : BCEWithLogitsLoss          # loss function name (ohemce, ce, dice)
  CLS_WEIGHTS   : false            # use class weights in loss calculation

OPTIMIZER:
  NAME          : adamw           # optimizer name
  LR            : 0.001           # initial learning rate used in optimizer
  WEIGHT_DECAY  : 0.01            # decay rate used in optimizer 

SCHEDULER:
  NAME          : warmuppolylr    # scheduler name
  POWER         : 0.9             # scheduler power
  WARMUP        : 10              # warmup epochs used in scheduler
  WARMUP_RATIO  : 0.1             # warmup ratio

EVAL:
  MODEL_PATH    : 'checkpoints/pretrained/FGMaxxVit/FGMaxxVit.FGMaxxVit.NMC.pth'  # trained model file path
  IMAGE_SIZE    : [384, 384]                                                            # evaluation image size in (h, w)                       
  # MSF: 
  #   ENABLE      : false                                                                 # multi-scale and flip evaluation  
  #   FLIP        : true                                                                  # use flip in evaluation  
  #   SCALES      : [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]                                     # scales used in MSF evaluation                

TEST:
  MODEL_PATH    : 'checkpoints/pretrained/FGMaxxVit/FGMaxxVit.FGMaxxVit.NMC.pth'  # trained model file path
  FILE          : 'assests/ade'                                                         # filename or foldername 
  IMAGE_SIZE    : [384, 384]                                                            # inference image size in (h, w)
  OVERLAY       : true                                                                  # save the overlay result (image_alpha+label_alpha)